// Code generated by Slice Machine. DO NOT EDIT.

import Hobbies from './Hobbies/index.svelte';
import Socials from './Socials/index.svelte';

export const components = {
	hobbies: Hobbies,
	socials: Socials
};
