// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = VisitekaartjeSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Title field in *page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *Visitekaartje → Primary*
 */
export interface VisitekaartjeSliceDefaultPrimary {
  /**
   * image field in *Visitekaartje → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: visitekaartje.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * over field in *Visitekaartje → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hallo wereld
   * - **API ID Path**: visitekaartje.primary.over
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  over: prismic.RichTextField;
}

/**
 * Default variation for Visitekaartje Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisitekaartjeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisitekaartjeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Visitekaartje*
 */
type VisitekaartjeSliceVariation = VisitekaartjeSliceDefault;

/**
 * Visitekaartje Shared Slice
 *
 * - **API ID**: `visitekaartje`
 * - **Description**: Visitekaartje
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisitekaartjeSlice = prismic.SharedSlice<
  "visitekaartje",
  VisitekaartjeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      VisitekaartjeSlice,
      VisitekaartjeSliceDefaultPrimary,
      VisitekaartjeSliceVariation,
      VisitekaartjeSliceDefault,
    };
  }
}
